In [6]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\hamza\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

In [3]:
business_path='C:\yelp_dataset\yelp_academic_dataset_business.json'
df_business=pd.read_json(business_path, lines=True)

In [4]:
display(df_business)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,AB,T6J 5H2,53.468419,-113.492054,3.0,13,1,"{'ByAppointmentOnly': 'False', 'RestaurantsPri...","Nail Salons, Beauty & Spas","{'Monday': '10:0-19:30', 'Tuesday': '10:0-19:3..."
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,TN,37204,36.115118,-86.766925,4.0,5,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Pets, Nurseries & Gardening, Pet Stores, Hobby...","{'Monday': '9:30-17:30', 'Tuesday': '9:30-17:3..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,IN,46250,39.908707,-86.065088,3.5,8,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Shopping, Jewelry, Piercing, Toy Stores, Beaut...",None
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,IL,62025,38.782351,-89.950558,4.0,24,1,"{'BusinessParking': '{'garage': False, 'street...","Fitness/Exercise Equipment, Eyewear & Optician...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,FL,33572,27.771002,-82.394910,4.5,9,1,"{'WheelchairAccessible': 'True', 'BusinessAcce...","Beauty & Spas, Permanent Makeup, Piercing, Tattoo","{'Tuesday': '12:0-19:0', 'Wednesday': '12:0-19..."

In [5]:
checkin_path='C:\yelp_dataset\yelp_academic_dataset_checkin.json'
df_checkin=pd.read_json(checkin_path, lines=True)

In [6]:
display(df_checkin)

,business_id,date
0,---kPU91CF4Lq2-WlRu9Lw,"2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020..."
1,--0iUa4sNDFiZFrAdIWhZQ,"2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011..."
2,--30_8IhuyMHbSOcNWd6DQ,"2013-06-14 23:29:17, 2014-08-13 23:20:22"
3,--7PUidqRWpRSpXebiyxTg,"2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012..."
4,--7jw19RH9JKXgFohspgQw,"2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014..."
...,...,...
131925,zznJox6-nmXlGYNWgTDwQQ,"2013-03-23 16:22:47, 2013-04-07 02:03:12, 2013..."
131926,zznZqH9CiAznbkV6fXyHWA,2021-06-12 01:16:12
131927,zzu6_r3DxBJuXcjnOYVdTw,"2011-05-24 01:35:13, 2012-01-01 23:44:33, 2012..."
131928,zzw66H6hVjXQEt0Js3Mo4A,"2016-12-03 23:33:26, 2018-12-02 19:08:45"
131929,zzyx5x0Z7xXWWvWnZFuxlQ,2015-01-06 17:51:53

In [7]:
def read_chunks(file, cols, chunk_size=500000):
    df = pd.read_json(
        f'C:\yelp_dataset\yelp_academic_dataset_{file}.json', chunksize = chunk_size, lines=True)
    
    chunk_list = [chunk[cols] for chunk in df ]

    return pd.concat(chunk_list, ignore_index = True, join = 'outer', axis = 0)

In [8]:
df_user = read_chunks('user', ['user_id','name','friends','fans'])

In [9]:
df_user

,user_id,name,friends,fans
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,"ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,"LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52
3,SZDeASXq7o05mMNLshsdIA,Gwen,"enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1
...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,None,0
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,None,0
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,None,0
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,None,0
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,None,0

In [10]:
df_business_PHIL = df_business[df_business['city'].str.lower().isin(['philadelphia'])]

In [11]:
df_business_PHIL

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
15,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,PA,19106,39.953949,-75.143226,4.0,245,1,"{'RestaurantsReservations': 'True', 'Restauran...","Sushi Bars, Restaurants, Japanese","{'Tuesday': '13:30-22:0', 'Wednesday': '13:30-..."
19,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,PA,19147,39.943223,-75.162568,4.5,205,1,"{'NoiseLevel': 'u'quiet'', 'GoodForMeal': '{'d...","Korean, Restaurants","{'Monday': '11:30-20:30', 'Tuesday': '11:30-20..."
28,QdN72BWoyFypdGJhhI5r7g,Bar One,767 S 9th St,Philadelphia,PA,19147,39.939825,-75.157447,4.0,65,0,"{'Smoking': 'u'no'', 'NoiseLevel': 'u'average'...","Cocktail Bars, Bars, Italian, Nightlife, Resta...","{'Monday': '16:0-0:0', 'Tuesday': '16:0-0:0', ..."
31,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,4105 Main St,Philadelphia,PA,19127,40.022466,-75.218314,3.0,41,0,"{'RestaurantsReservations': 'False', 'Caters':...","Pizza, Restaurants, Salad, Soup","{'Tuesday': '17:0-21:30', 'Wednesday': '17:0-1..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150320,wPAaAbFbq5wfLfW0gnYU7g,Intermix,1718 Walnut St,Philadelphia,PA,19103,39.950060,-75.170129,2.0,10,0,"{'BusinessParking': '{'garage': False, 'street...","Fashion, Shopping, Women's Clothing","{'Monday': '10:0-19:0', 'Tuesday': '10:0-19:0'..."
150326,JDM7kiCEmeBc_5W-z6eZZw,2601 Parkway Apartments,2601 Pennsylvania Ave,Philadelphia,PA,19130,39.968806,-75.180608,3.0,6,1,{'BusinessAcceptsCreditCards': 'True'},"Real Estate, Apartments, Home Services",None
150329,9U1Igcpe954LoWZRmNc-zg,Hand & Stone Massage And Facial Spa,"1100 S Columbus Blvd, Ste 24",Philadelphia,PA,19147,39.932756,-75.144504,3.0,32,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Day Spas, Beauty & Spas, Skin Care, Massage","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ..."
150334,LJ4GjQ1HL6kqvIPpNUNNaQ,Shanti Yoga and Ayurveda,"1638 Pine St, Fl 1",Philadelphia,PA,19103,39.945966,-75.169666,4.5,39,1,"{'ByAppointmentOnly': 'True', 'GoodForKids': '...","Health & Medical, Yoga, Shopping, Naturopathic...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,Philadelphia,PA,19147,39.935982,-75.158665,4.5,35,1,"{'WheelchairAccessible': 'False', 'Restaurants...","Restaurants, Mexican","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."

In [12]:
df_review = read_chunks('review', ['review_id','user_id','business_id','stars'])

In [13]:
df_review

,review_id,user_id,business_id,stars
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4
...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3

In [14]:
df_review_PHIL=df_review[df_review['business_id'].isin(df_business_PHIL['business_id'])]

In [15]:
df_review_PHIL

,review_id,user_id,business_id,stars
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1
13,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4
16,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5
...,...,...,...,...
6990257,tWCi4N2qCil876BI2NDAZg,5d32aJe0a3_fSl3LIVYkWQ,EmrOCT7fArKI0JI_XF6aaw,1
6990260,nLjbVsETpqO17RbFcqskkA,am7-gkH_PDz598oTdYSD6A,3gVSrS4kffGGZT8oXHsIcw,3
6990263,99ylx-qPUSseITqBye2MpA,-AkziDwQ8hv2COTDBBUpig,aunmz06iWvo3bd6MMHEbqg,3
6990265,KlHxcAifUF5zDKpJCBrRsw,7ziWZULyiZv2TesYNMFf4g,qQO7ErS_RAN4Vs1uX0L55Q,4
6990269,cACxcUY_AIsQKkpDRXuqnw,MCzlzlOw7IGbRAKVjJBPtg,fcGexL5VH5G2Xw0tRj9uOQ,3

In [16]:
df_user_PHIL=df_user[df_user['user_id'].isin(df_review_PHIL['user_id'].unique())]

In [17]:
df_user_PHIL

,user_id,name,friends,fans
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,"ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138
5,q_QQ5kBBwlCcbL1s4NVK3g,Jane,"xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357
9,AUi8MPWJ0mLkMfwbui27lg,John,"gy5fWeSv3Gamuq9Ox4MV4g, lMr3LWU6kPFLTmCpDkACxg...",4
14,1McG5Rn_UDkmlkZOrsdptg,Teresa,"piejMEdRkGB7-1aL4lL5NQ, X0zFOU6iG95-feQKOXkgrA...",1
...,...,...,...,...
1987832,iZ0puydkFQlaSQAXbGtv1g,Dr. Sylvia,None,0
1987834,XTWARBzLbiJKQ1JeJB9f3g,Sakina,None,0
1987859,K-BNvWUCWEGUuBirCU4mmg,Jodi,None,0
1987862,cu_xPeMTm8qsWShBIHJeuw,Susan,None,0
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,None,0

In [18]:
len(df_review_PHIL['business_id'].unique())

14576

In [19]:
# Extract friends' user IDs from the filtered users
all_friends_user_ids = df_user_PHIL['friends'].str.split(', ').explode().unique()

In [20]:
df_user_and_friends_PHIL=df_user[df_user['user_id'].isin(all_friends_user_ids) | df_user['user_id'].isin(df_user_PHIL['user_id'])]

In [21]:
df_user_and_friends_PHIL

,user_id,name,friends,fans
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,"ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,"LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52
3,SZDeASXq7o05mMNLshsdIA,Gwen,"enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28
5,q_QQ5kBBwlCcbL1s4NVK3g,Jane,"xBDpTUbai0DXrvxCe3X16Q, 7GPNBO496aecrjJfW6UWtg...",1357
...,...,...,...,...
1987832,iZ0puydkFQlaSQAXbGtv1g,Dr. Sylvia,None,0
1987834,XTWARBzLbiJKQ1JeJB9f3g,Sakina,None,0
1987859,K-BNvWUCWEGUuBirCU4mmg,Jodi,None,0
1987862,cu_xPeMTm8qsWShBIHJeuw,Susan,None,0
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,None,0

In [30]:
import surprise

In [32]:
from surprise import Dataset, Reader, NormalPredictor, KNNBasic, KNNWithZScore, KNNWithMeans, KNNWithZScore, SVD
from surprise.model_selection import train_test_split, cross_validate
from collections import defaultdict
from surprise import accuracy

In [33]:
df_reviews_and_friends_PHIL=df_review[df_review['user_id'].isin(df_review_PHIL['user_id'])|df_review['user_id'].isin(all_friends_user_ids)]

In [34]:
df_reviews_and_friends_PHIL

,review_id,user_id,business_id,stars
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5
5,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1
...,...,...,...,...
6990275,H0RIamZu0B0Ei0P4aeh3sQ,qskILQ3k0I_qcCMI-k6_QQ,jals67o91gcrD4DC81Vk6w,5
6990276,shTPgbgdwTHSuU67mGCmZQ,Zo0th2m8Ez4gLSbHftiQvg,2vLksaMmSEcGbjI5gywpZA,5
6990277,YNfNhgZlaaCO5Q_YJR4rEw,mm6E4FbCMwJmb7kPDZ5v2Q,R1khUUxidqfaJmcpmGd4aw,4
6990278,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5
6990279,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3

In [37]:
cities=df_business['city'].unique()
for city in cities :
    print(city)

Santa Barbara
Affton
Tucson
Philadelphia
Green Lane
Ashland City
Brentwood
St. Petersburg
Nashville
Land O' Lakes
Tampa Bay
Indianapolis
Clearwater
Largo
New Orleans
Kenner
Edmonton
Reno
Newtown
White House
Boise
Paoli
Ardmore
Exton
Wilmington
Edwardsville
Sparks
Alton
Cherry Hill
Bala Cynwyd
Springfield
Belleville
Carmel
Tampa
Kennett Square
Plymouth Meeting
Harvey
West Chester
Meridian
Hudson
Fernley
Williamstown
Pinellas Park
Glenolden
Wesley Chapel
Fishers
Burlington
Troy
Camden
Plainfield
Bensalem
Maplewood
Saint Louis
Fairview Heights
Oro Valley
Treasure Island
Southampton
Chalfont
Willow Grove
Voorhees
Tarpon Springs
Blue Bell
Metairie
Woodbury
Brownsburg
Norristown
Land O Lakes
Greenwood
Saint Petersburg
Brookhaven
Haverford
Glenside
Moorestown
Madison
Ewing
Levittown
Gloucester Township
Aston
Riverview
Warrington
Wyncote
St. Louis
Havertown
Madeira Beach
Lutz
Langhorne
King of Prussia
Smithton
Jenkintown
New Port Richey
Avon
Normandy
Wayne
Franklin
Tuscon
Brandon
Berwyn
TAMPA
St Albert
Terra Ceia
Delaware County
Hermitage
Doylestown
Temple Terrace
Downingtown
Sherwood Park
Virginia City
Trenton
Bellmawr
Marana
Belle Chasse
Somerdale
Warminster
Smyrna
Chester
Odessa
Horsham
Valley Forge
Apollo Beach
Malvern
Maple Shade
Lansdale
St. Pete Beach
Ballwin
Cedarbrook
Spring Hill
Goodlettsville
Villanova
Holiday
Narberth
Oldsmar
Bristol
Isla Vista
Perkiomenville
Seminole
Gulfport
Glassboro
Haddonfield
Montgomeryville
Chesterfield
Fenton
Pennsville
Haddon Heights
Morrisville
Goleta
Hazelwood
View
North Wales
Upper Darby
Elkins Park
Medford
St Louis
Kingston Springs
Noblesville
Mullica Hill
Palmyra
New Hope
St Petersburg
Mount Juliet
Buckingham
Mt. Juliet
Media
Saint Charles
Chalmette
High Ridge
Conshohocken
Hernando Beach
Florissant
Sicklerville
University City
Mooresville
Chadds Ford
Woodstown
Plant City
Catalina Foothills
Spring HIll
O Fallon
Ruskin
Town and Country
Lebanon
Bridgeton
Skippack
Bryn Mawr
Safety Harbor
Jennings
Eagle
Feasterville
Pottstown
Carpinteria
Marlton
Spring City
Valrico
Riverside
Lambertville
Creve Coeur
Green Valley
Ambler
Manchester
Hatfield
St. Charles
Clementon
Montecito
Godfrey
Florence Township
Mascoutah
Trinity
Sewell
King Of Prussia
Yardley
Delran
St. Davids
Newark
Primos
Huntingdon Valley
Bellair
Collingswood
Marrero
Mount Laurel
Collingdale
Fort Washington
Hendersonville
Silverdale
Limerick
Haddon Township
Cinnaminson
Lionville
Oreland
Turnersville
Westwego
Prospect Park
Cahokia
Port Richey
Atco
Fountainville
Collegeville
Royersford
Dunedin
Bridgeport
Mount Laurel Township
Glen Carbon
Roslyn
West Berlin
Huntingdon Valley PA
Washington Crossing
Zionsville
St Charles
Drexel Hill
Verdi
Riverton
Folsom
Town 'n' Country
Clearwater Beach
Harleysville
St Pete Beach
Lawnside
Pleasant View
Arnold
Thorndale
Seffner
Kimberton
East Norriton
Zephyrhills
Maryland Heights
Overland
Schwenksville
Granite City
Dublin
Harahan
Warson Woods
Flourtown
Old Hickory
Sun City Center
Franklinville
Palm Harbor
Voorhees Township
Oaks
Phoenixville
NASHVILLE
Temple Terr
Pitman
Line Lexington
Runnemede
Hockessin
Newtown Square
St. Albert
Ferguson
Gretna
Fairless Hills
Clifton Heights
Des Peres
Pennsauken
Trooper
North Redington Beach
Ridley Park
Earth City
Woodlyn
Avondale
Lumberton
Hatboro
Lahaska
Westville
Boothwyn
Woolwich Twp
Saint Ann
Kulpsville
Newport
Shiloh
Waterloo
Washington Township
Wyndmoor
Brooklawn
Abington
Berlin
Darby
Bellevue
Glen Mills
Souderton
Gallatin
Kirkwood
Speedway
Rosemont
Berkeley
Broomall
La Vergne
Mount Holly
Perkasie
New Castle
Lithia
Barrington
Deptford Township
Erdenheim
Westmont
Greenbrier
Pontoon Beach
Lawrence
Sharon Hill
Swedesboro
Cheltenham
Whiteland
Belleair
Antioch
Eddystone
East Greenville
Sellersville
Jefferson
Evesham Township
Webster Groves
Freeburg
Swarthmore
Frazer
Ewing Township
Camby
Audubon
Greater Northdale
Shrewsbury
Oaklyn
Richmond Heights
Collinsville
Mulberry
Woodbury Heights
Deptford
Town & Country
Hamilton
Whitestown
Willingboro Township
Gibbsboro
Glendora
Stowe
Morton
Beaumont
Dover
O'Fallon
Sauget
Elmer
Swansea
Lansdowne
Garden City
Blackwood
Columbus
Richboro
Thonotosassa
Feasterville-Trevose
Glenmoore
Holmes
Wenonah
Quakertown
Mount Ephraim
Hainesport
Penns Grove
Gilbertsville
Hamilton Township
Land o lakes
Claymont
Imperial
Essington
Gibsonton
Arabi
Eagleville
Mendenhall
Clayton
Maryville
Dresher
Penndel
Saint Pete Beach
River Ridge
Columbia
Crestwood
ST. Louis
Land O'Lakes
Lindenwold
Douglassville
Bosie
Maple Shade Township
Redington Shores
Bordentown
Colmar
Secane
santa Barbara
Terrytown
Lafayette Hill
Drexel
abington
Telford
St.Ann
Elverson
Rockledge
Mickleton
Greenville
Willingboro
East Saint Louis
Woolwich Township
Crum Lynne
Hilltown
Spring House
Laurel Springs
Croydon
Merchantville
Spanish Springs
Westampton
Wimauma
Erial
Mt Juliet
McCordsville
Trappe
Shamong
West Deptford
Olivette
Treasure Is
Secane
Mt. Laurel
Furlong
Oracle
Pass-a-Grille
Norriton
Maryville
Wood River
Mount Royal
Danville
Sahuarita
Beech Grove
Petersburg
Trevose
Paulsboro
Palmetto
New Palestine
Millstadt
Holland
New castle
Valley Park
Jamison
Yeadon
Dupo
Plumsteadville
Mt Laurel
Mont Clare
Primos-Secane
Audubon
Sun Valley
Indian Rocks Beach
Scott AFB
Jobstown
Flanders
Nashville-Davidson metropolitan government (balance)
Wallingford
Wynnewood
East Lake
Nolensville
NEW PORT RICHEY
Philadephia
Boyertown
Tabernacle
Vineland
Caseyville
Reno
Magnolia
Lester
Vail
Florence
Hillsborough County
Mansfield
South Cinnaminson
Garnet Valley
Maple Glen
Chester Springs
Ybor City
Ladue
Edmundson
Masaryktown
Saint Davids
Truckee
Waterford Works
Tuson
Belleair Bluffs
Penn Valley
Belmont Hills
Southport
Radnor
St.Rose
Lawrenceville
Glenn Mills
Arizona
Bear
Newfield
Santa Barbara
Saint Albert
Indian Shores
Hammonton
South Pasadena
Folcroft
Gloucester City
Webster Grvs
West Conshohocken
Devon
phoenixville
Meterie
Evesham
Berlin Township
Redingtn Shor
Feasterville Trevose
Monroe Township
Pennsburg
Frontenac
New Britain
SPARKS
New Prt Rchy
Churchville
Elsmere
Boone
Mercerville
Rock Hill
Linwood
Stratford
Merion Park
Belle Chase
Abington Township
Twin Oaks
Dade City
Fairmount Park
lutz
NW Edmonton
Star
Staint Albert
Sun City
O'fallon
Chesterbrook
Coatesville
Merion Station
Murfreesboro
Salem
Titusville
Bridge City
Ventura
Lavergne
Indianpolis
Pittsgrove Township
Spokane
Logan Township
Talleyville
Roebling
Elmwood
KIRKWOOD
West Norriton
Meadowbrook
Brooksville
Westtown
Sanatoga
St Louis Downtown
Lemay
Ellisville
PHILA
Oakville
Westchase
Westampton Township
Lula Lula
Sunset Hills
TWN N CNTRY
Jeffersonville
Edgewater Park
Breckenridge Hills
Holland Southampton
Pike Creek
Balm
Royford
Pipersville
clearwater
Delanco
St.Louis
Milmont Park
Upper Darby PA
East Lansdowne
Marcus Hook
Lederach
Lemay Ferry
Bywater
Kenneth City
Spruce Grove
Thorofare
Carneys Point
telford
Town & County
Carrollwood
Dumont
Trainer
Southeastern
Twn N Cntry
Pennington
Kuna
Town And Country
Upper Southampton Township
NEW ORLEANS
West Edmonton
East Alton
Concordville
RENO
Red Hill
National Park
Greenfield
Unionville
Bucks
Montgomery
New Jersey
Bryn Athyn
East Norristown
Mantua Township
TUCSON
Clarksboro
Tinicum
sparks
Southeast Edmonton
Jefferson Parish
East St Louis
Eastampton
St Ann
Pagedale
Upper Pittsgrove
Springhill
Burlington Township
Summerland
Harrison Township
Fairless
W.Chester
Scott Air Force Base
Pinecrest West Park
Toughkenamon
Plymouth Township
W Cherry Hill
Aldan
Pass-a-Grille Beach
Southwest Philadelphia
Pemberton
Central Tampa
Tierra Verde
lawrence
Washoe Valley
Clermont
Indianapolis
Pennsauken Township
Hadden
Almonesson
wilmington
Birchrunville
VALRICO
Joelton
New Pt Richey
Port Hueneme
RENO AP
Mount Lemmon
Norwood
saint petersburg
St. Ann
Charlack
Pegram
Boise City
Tucson
Lawrence Township
Ozona
Mehville
Pittsgrove
Erdenheim Pa
Pine Hill
Mandeville
Saintt Petersburg
Bellville
Rosewood Heights
Haddon Twp
East Nashville
Marlborough
East St. Louis
Cortaro
Worcester
Upper Chichester
Berry Hill
Ashland
South County
Bethalto
Valencia West
Tullytown
Saint louis
Mantua
Holicong
Phila
Saint John
Boise (Meridian)
Rillito
Winslow
Pine HIll
Fairview Hts.
Gwynedd Valley
Ste C
Philadelphia PA
EdMonton
Meridan
Ridley
Violet
Catalina
Feasterville-trevose
Upper Gwynedd
Hartsville
SAINT LOUIS
Haddon
metairie
Pilesgrove
West Deptford Townsh
Inglewood
Summerhaven
Parkside
Yardley Boro
Chestnut Hill
Meraux
Malaga
West Hill
Southwest Tampa
St. Pete
Oldmans
Castleton
YARDLEY
Cedar Brook
Newtown Township
Santa Ynez
MERIDIAN
Casa Adobes
Medford Lakes
WEST CHESTER
clifton heights
Mt. Ephraim
Marshallton
riverview
Ivyland
​Largo
Christiana
Beverly
Melrose Park
boise
Bordentown Township
Hulmeville
S Pasadena
Pennsville Township
Southampton Township
Oaklandon
Mccordsville
Sappington
Town n Country
Wyndlake Condominium
College Place
St.louis
Bensalem Township
Ridley Township
LOWER PROVIDENCE
Mc Cordsville
Corona de Tucson
Washington Park
San Antonio
Palm harbor
Creve Couer
land o lakes
French Quarter
Lower Gwynedd Township
Waggaman
Rose Valley
East Tampa
Luling
Zieglerville
NORRISTOWN
Kings Beach
Bradenton
Donelson
Covington
Pennsaulen
Woodson Terrace
Meridian
St Pete
Mission Canyon
Arrington
Franconia
Bargersville
West Alton
Nashville,
Mt Laurel Twp, NJ
Gibbstown
Saint Petersburg,
Philadelphila
Citrus Park
Gladwyne
Houston
NEW PRT RCHY
Tren
Skippack Village
West Mount Holly
Upland
New orleans
CREVE COEUR
Horseshoe Bend
OFallon
New Berlinville
CLEARWATER BEACH
Hilltop
Saint Rose
Tampa - North
Beech Grove,
INDIANAPOLIS
Gradyville
erdenheim
Thonosassa
Elk Township
franklin
Devon-Berwyn
AMBLER
Vincentown
Manayunk
PHILADELPHIA
Indian Rocks Beach.
Bethel
tucson
Eaux Claires
St  Louis
Los Angeles
Glenoldan
Wesley chapel
Tucson, Arizona
Clearwater,
Edgmont
Reno Nevada
reno
Winslow Township
Concord Township
Blvd
North Redington Bch
Hartford
maple shade nj
Parker Ford
Had Twp
Westmont - Haddon Towsship
Westfield
St Rose
Wilmington Manor
Yorklyn
Saint Bernard
Rushland
West Trenton
Denver
Cheltenham Township
Lansdale
Crosswicks
RIVERVIEW
Wrightstown
Mt Holly
Carversville
CLEARWATER
Green Park
St Petersberg
Zephryhills
Cornwells Heights
VC Highlands
St. Loius
largo
indianopolis
Palm Harbor, FL
NEWARK
Echelon
South Roxana
LARGO
Cottage Hills
Oakford
St.Petersburg
ST LOUIS
Belleair Blf
Tampa Florida
Bristol Twp
Kenneth
Pilgrim Gardens
Trolley Square
LANSDALE
Kalispell
North Marlton
Glendale
Tarpon springs
Moorestown-Lenola
Bayonet Point
Tampa Terrace
Pineville
St. Rose
​Clayton
Lake Saint Louis
Mehlville
Shady Hills
Bethel Township
Cherry Hil
Eagle,
Andalusia
Mt Laurel Township
West  Deptford
Belle Meade
Ofallon
West Point
NASHVILLE AP
Zieglersville
Cold Springs
Washington Twp
Woodbourne
Saint Louis
Lower Gwynedd
Earlington
MADISON
Riveridge
Whites Creek
Oxnard
Center City Philadelphia
North Coventry
Lower Merion
Chesilhurst
Land-O-Lakes
Rural Hill
Fairview Hts
St louis
Centreville
Warwick
Strafford
​Lithia
Quinton
Cerritos
Claerwater
Eastampton Township
South Tucson
Woolwich Twp.
Nashville
Downingtown,
Radnor Township
Mechanicsville
Black Jack
New Whiteland
Downtown
Roseville
Saint Petersburg Beach
St. Peters
Feastville
Chicago
Oldmans Township
Wanamaker
Pinellas park
Mt. Holly
Phonixville
Kimmswick
Saint Peters
Nixa
Freehold
Pilot Sound Area West Portion
Gentilly
pennsauken
Hamiltion
Redington Beach
Newtown square
Belleair Beach
Lutz fl
Gwynedd
COLMAR
Nevada
Chester Township
Montgomery Township
Fortville
meridian
Fairview
Gardenville
Safety  Harbor
Pleasant Township
Thornton
Pinellas
FOLSOM
Roxborough
Gulph Mills
Bucks County
SPRINGHILL
Danboro
Pasadena
ST. PETE BEACH
Mt Ephraim
Forest Grove
King of Prussi
Drexel Hil
Casas Adobes
Hancock
Mt. Airy
Swedesboro
Hampton
Eddington
Hillsborough
Stroudsburg
Washington
Downtown Indianapolis
SEMINOLE
Santa Clara
Wayne/Radnor
Mt.Laurel
Mt.Juliet
Monroeville
sewell
Crystal Beach
Mississauga
Brentwood - Cool Springs
kop
Virtual
Sassamansville
Fox Street
AVON
Upper Merion Township
Washoe
Cumberland
Fairview Village
Boise
tampa
TARPON SPRINGS
Sparks
Conshohoeken
Norritown
Barnhart
langhorne
River View
Santa Rita
Linfield
Peerless Park
DUNEDIN
HUdson
Bradenton Beach
Pottsgrove
Nampa
E Saint Louis
San Anselmo
Warrington Township
Dunedin
St Pete beach
Knoxville
N Redington Bch
Roxana
Drexel Heights
Valencia
Fairmont City
New Orlaens
Sturgeon Couny
E. Norristown
Richwood
chicago
Crystal Springs
Whitehouse
Sparks NV
Feasterville-Trevose, PA
West Philadelphia
Forest Hills
Shade
Picture Rocks
Los Ranchitos
Cedars
Deptford Twp
Montchanin
Solebury
Belleair Blufs
Hi-Nella
Real Goleta
Center Square
O' Fallon
Southampton
MIDDLE CITY WEST
Bucktown
Landsdale
wimauma
Newton Square
Dunnellon
Tampa Palms
Brooklyn
West Chester PA
Cherry Hill,
Chalemette
Wilmington
Grenloch
Lima
Mango
Santa Barbara,
Royersford
East Edmonton
Tylersport
Tampa - South
Carson City
Evshm Twp
ST. PETERSBURG
McCarran
Delran Twp
Algiers
Lenni
Scott Afb
Martinsville
Edgemoor
Glenmore
Feasterville Trev
Saint Louis
Penllyn
Upper Southampton
Aliso Viejo
Largo (Walsingham)
Sarasota
Sumneytown
Pennsylvania
frazer
Delray Beach
N Redngtn Bch
North Maple Shade
Land o Lakes
Palm harbor
Boulevard
Monrovia
Green Hills
Carney's Point
new orleans
Cynwyd
Honey Brook
Greater Carrollwood
Enoch
LITHIA
POTTSTOWN
Edgemont
Chester Heights
Lakeland
LOWER MERION
BRANDON
SAINT LOUIS AP
TRENTON
St Louis County
philadelphia
University Park
quakertown
ClearWater
Metarie
saint ann
elmwood
Afton
South Harrison Township
Arden
horsham
Town N Country
New Washoe City
West Bradford Township
SANTA BARBARA AP
Austin
Reno City
Bridgeton
MEDIA
St.Pete Beach
Tampla
GARDEN CITY
Nolenville
Stead
Kimmiswick
Old Strathcona
South Tampa
South Lake Tahoe
Cornwells Hts
Buckingham Township
Fieldsboro
ARDMORE
Festerville
Liverpool
Franklin
Pedricktown
DONELSON
Goodletsville
Redingtn Shores
Falls
Santa Barbara & Ventura Counties
Cane Ridge
Havertown, PA
Metairie
BOISE AP
Belleville
Hopewell Township
Southhampton
Delaware
Zionsville In
Santa Barbra
North Coventry Township
Sherwood
Corona De Tucson
Land o' Lakes,
French Quarter - CBD
Pine Forge
Newportville
NORTH WALES
Philiidelphia
SAINT PETERSBURG
New Britian
Lower Southampton Township
Huntington Valley
Indianapolis,
Newcastle
Hi Nella
Stone Harbor
Nsshville
East Falls
Lakewood
Haddon township
SANTA BARBARA
Bensalem. Pa
Riverview Fl
Elfers
NEW ORLEANS AP
South Burlington
Haverford,
Newtown Sqaure
Alberta Park Industrial
Bellefontaine
Westhampton
nashville
Chichester
Bellefontaine Neighbors
Upper Pottsgrove
Indianapolis city (balance)
W. Berlin
Tinicum Township
Brentwood
Town and Country
South Reno
Fairland
Berlin Boro
Winterthur
gilbertsville
Winchester
Blooming Glen
Maryland Height, MO
Dellwood
Safety Harbor,
Oro valley
wesley chapel
Old Hickory, TN
Wesley Chapel
Ewing Twp
Wesley Ccapel
AB Edmonton
Saint Louis,
CHESTER HEIGHTS
Indiana
St Petersurg
Tampa
BOISE
Gloucester
Warminster
Wilimington
Green Valle
Twin oaks
Boutte
Blackwood
Mt  Juliet
Madiera Beach
Haverford
Lincoln
West Norriton
Plainfiled
CLIFTON HEIGHTS
DELRAN
St. Petersberg
PINELLAS PARK
Telford
LANGHORNE
St.Charles
DOWNINGTOWN
TRINITY
Philly
Saint Leo
South Madison
Alloway
Cherry Hill Mall
Tierre Verde
Maran
Stanton
Fort Saskatchewan
Philadelphia (Northeast Philly)
MARLTON
Landsale
Foster Pond
Newtown Sq.
Costa Mesa
Frederick
UPPR BLCK EDY
Lynnfield
CONSHOHOCKEN
Wycombe
Santa  Barbara
Swedeland
Tennesse
West Collingswood Heights
Tampa,Fl
Barto
Boston
N.Wales
Creamery
Sparks,
Merion
St Boise
Sullivan
goodlettsville
Bel Ridge
West Rockhill
Haverton
London Grove
Salinas
INpolis
Clarksville
Rutledge
Delran Township
Concord Village
Carpinteria
spring city
Land O'lakes
TUCSON AP
Tampa,
spring hill
Johnson
St. Leo
Hurffville
Kirklyn
Overbrook
New Tampa
Edmonton City Centre
Macdill Afb
Charles
Tortola
Kng Of Prusia
Newtown Sq
Redington Shore
Philadelphia
Clearwater/ Countryside
Pasco
East Boise
South Cherry Hill
nolensville
Williamsport
Caln
Fallsington
Apopka
TEMPLE TERR
TAMPA AP
RADNOR
Safety Hatbor
MANCHESTER
St. Louis County
West Nashville
Santa Maria
kenner
Hollywood
East Norriton
Hernando Bch
WILLOW GROVE
Chattanooga
Rancocas
Bennington
Middletown
Philiadelphia
Spark
Bellefonte
Town 'N' Country
Newton
S.Pasadena
CHELTENHAM
Lower Southampton
Monchanin
Wesley Chapel  FL
Maryland Height
MacDill AFB
PLYMOUTH MTNG
Monroe
HENDERSONVILLE
Reno Sparks
St.  Charles
Charlotte
Key Largo
Woodbury Hts.
Mount Holly,
Slidell
Wales
UPPER MORELAND
Apollo beach

In [161]:
dfb_franklin=df_business[df_business['city'].str.lower().isin(['franklin'])]

In [162]:
dfr_franklin=df_review[df_review['business_id'].isin(dfb_franklin['business_id'])]

In [163]:
dfu_franklin=df_user[df_user['user_id'].isin(dfr_franklin['user_id'].unique())]

In [165]:
dfu_franklin

,user_id,name,friends,fans
26,kggqL33iZjeHmUn1Rtdjzg,Jay,"5-cF_paDOoXPtgaAeE_XyQ, bwPqqPZ0u5ak_Lr45V1-CQ...",9
37,KYBEVBAP7QUlt1LjmatTJg,Matthew,"B7ecAeAIrXg7sgmabS38pg, tLrEDEs1Zu5NNmVuUivxvA...",63
38,QJI9OSEn6ujRCtrX06vs1w,J,"RyPeT_ICAtX8ah9dhDpEFw, W8r4aKPZFT3GPIQQDbqB6Q...",316
60,LwZJFLGxQwjjeOgpqTJnfw,Lucas,"RHsmgIvCfnFL7DPNptKY8A, mObXpXBnaOV_UhE0gWwvPQ...",5
145,8zkkuk8KOoNojZhTx0j5KA,Melissa,"p-lbHRoUAPC0OWmOXtzNIA, 0EXuIg5v5rnQzGh8P8uRKw...",11
...,...,...,...,...
1987345,_zAH1G-sp3uNb9CGbY6mmQ,Jim,None,0
1987384,J5s1-bXtrYfhfDjLkEvnYw,Karry,None,0
1987558,b-FmQDc3uNtg7-WhS4wElQ,Celia,None,0
1987578,WXIaXyUFuP8Ci2CtehtBFA,Dana,None,0
1987624,2_q6zwXALVA3uBMIPJcR7Q,Susan,None,0

In [166]:
dfr_franklin

,review_id,user_id,business_id,stars
406,89SF8MFoiY4mIhOgzAMVhA,S8rqFLdHCFAeibs52a4QpQ,kKk_2OAnCRbxX5rLqQYBHg,5
425,HyD8P-CcFU3FR75T0dJAhA,YsaJXW7VWV2bhoN5tokKrg,HCqmx4ENAZ76SAjoalj-MQ,4
693,3B41BdxNIENFP1EsCCybnw,B0fzg0eUWplNBzfSJsCFDg,VUOD8yD1jwq_pqRP8EETBQ,3
802,h0N47vwJhQMBH9mscX9zhw,11jQWQYTJkzIE6o3s5ID4Q,hn3Rg2JrhQoDJBEhrpuwWg,1
804,cgppGTg8LpqZObn_k69w2Q,TSxzAqKzU2OvjWSLoSU8dA,skN2XhKXlcjf53uIwzAedw,5
...,...,...,...,...
6989373,Rjv4qf02STIbSUu5mq4W4w,U0kiORl1Gpc8K9jOWWgHzg,yi5VHfhTIPopCob2toQH8A,1
6989504,B50r7a0YV-WnBgf3bW-Dyw,H9AGj0t3ghPaHug0Ri3kOQ,y8AENR609baGvVe-d_F-dg,1
6989863,lbhfWHGz3C6dyLp_aiKadg,EUITvLX8HgKpJPs8ngXRPw,7rxLUgFNwAWd69Y4iZnUCA,5
6990131,sXMx4wAegK38PRbzyWe5Bg,4Ry0q14UDewv2LMa2wibCQ,IoRTm7IAJqBbHpiisUBnLg,4
6990230,4ncWtKqNnGcpHk2isnWZzg,jM9eD_bmcthFWliBUnWSLA,IoRTm7IAJqBbHpiisUBnLg,5

In [167]:
dfb_franklin

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
245,uDQgmudYDKiB6n4vwbEeDg,Chrysalis,9040 Carothers Pkwy,Franklin,TN,37067,35.956533,-86.802720,4.5,112,1,"{'HasTV': 'False', 'WiFi': 'u'free'', 'Busines...","Restaurants, Italian, Nightlife, Bars, Cocktai...","{'Monday': '0:0-0:0', 'Tuesday': '11:0-21:0', ..."
309,96qKAK06EdkG6GPVxKDdTw,Goin' Postal Westhaven,"188 Front St, Ste 116, Westhaven Town Center",Franklin,TN,37064,35.929205,-86.919592,3.5,16,1,"{'BusinessAcceptsBitcoin': 'False', 'BusinessA...","Shipping Centers, Notaries, Local Services, Pr...","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
316,1E9o1SNo7UTf1XHTFPv1_Q,Franklin Juice Co,"230 Franklin Rd, Ste 11W",Franklin,TN,37064,35.932605,-86.860662,4.5,66,1,"{'Ambience': '{'romantic': False, 'intimate': ...","Restaurants, Acai Bowls, Vegan, Organic Stores...","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
512,PENtXTN19SYMMmFYYbA_Gw,Lubrication Corner,705 Columbia Ave,Franklin,TN,37064,35.922235,-86.871725,5.0,5,1,None,"Oil Change Stations, Auto Repair, Automotive","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
567,1s-vqaaGLscl7h4XIDO7LQ,Brilliant Nail Spa,"4091 Mallory Ln, Ste 106",Franklin,TN,37067,35.932651,-86.824633,4.0,74,1,"{'RestaurantsPriceRange2': '2', 'BikeParking':...","Beauty & Spas, Hair Removal, Skin Care, Waxing...","{'Monday': '9:30-19:0', 'Tuesday': '9:30-19:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149806,9BVO07g5PruWhckWtTdL4w,Enterprise Rent-A-Car,284 Mallory Station Rd,Franklin,TN,37067,35.955894,-86.827248,4.5,6,1,None,"Hotels & Travel, Car Rental","{'Monday': '0:0-0:0', 'Tuesday': '7:30-18:0', ..."
149901,SMrEjrZ9zH53DT5mN5Is9A,Lunatic Fringe Salon - Franklin,"1109 Davenport Blvd, Ste 300",Franklin,TN,37069,35.971184,-86.835770,4.5,24,0,"{'BikeParking': 'True', 'RestaurantsPriceRange...","Beauty & Spas, Hair Salons","{'Monday': '9:0-15:0', 'Tuesday': '8:0-20:0', ..."
149929,tiYGClVGXW4tGrJVHHkOVQ,Whit's Frozen Custard,"4020 Hughes Crossing, Ste 100",Franklin,TN,37064,35.862750,-86.844741,4.5,68,1,"{'BikeParking': 'True', 'WiFi': ''no'', 'Busin...","Food, Ice Cream & Frozen Yogurt, Desserts","{'Monday': '0:0-0:0', 'Tuesday': '12:0-21:0', ..."
149943,rhTLD0ZUfdNjluBUFX79eQ,D1 Sports Training,7115 South Springs Dr,Franklin,TN,37067,35.951961,-86.815031,4.0,13,1,{'GoodForKids': 'True'},"Physical Therapy, Fitness & Instruction, Activ...","{'Monday': '5:0-20:0', 'Tuesday': '5:0-20:0', ..."
150033,rhYObnJD91kq_b8qk5pU7g,Sky Zone Trampoline Park,"1113 Murfreesboro Rd, Ste 254",Franklin,TN,37064,35.918469,-86.837068,3.5,10,0,"{'BikeParking': 'False', 'ByAppointmentOnly': ...","Kids Activities, Active Life, Venues & Event S...","{'Tuesday': '16:0-20:0', 'Wednesday': '16:0-20..."